# Generated by Django 5.2.10 on 2026-02-06 13:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Вариант 1 - Иванов', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сессия вычислений',
                'verbose_name_plural': 'Сессии вычислений',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='formulas.category', verbose_name='Родительская категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Уникальный идентификатор (например: K, Re, alpha1)', max_length=50, validators=[django.core.validators.RegexValidator(message='Символ должен начинаться с буквы и содержать только латинские буквы, цифры и подчёркивание', regex='^[a-zA-Z_][a-zA-Z0-9_]*$')], verbose_name='Символ')),
                ('name', models.CharField(help_text='Понятное название формулы', max_length=200, verbose_name='Название')),
                ('expression', models.TextField(blank=True, default='', help_text='Математическое выражение (например: R1 * (1 - cos(alpha)))', verbose_name='Выражение')),
                ('unit', models.CharField(blank=True, help_text='Единица измерения результата (например: м, кг, Вт)', max_length=50, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, help_text='Подробное описание формулы', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_input', models.BooleanField(default=False, help_text='Если отмечено - это входное значение, а не вычисляемая формула', verbose_name='Входной параметр')),
                ('default_value', models.FloatField(blank=True, null=True, verbose_name='Значение по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulas', to='formulas.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулы',
                'ordering': ['category', 'order', 'symbol'],
                'unique_together': {('user', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='FormulaChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название графика')),
                ('x_variable', models.CharField(help_text='Символ переменной для оси X', max_length=50, verbose_name='Переменная по оси X')),
                ('x_min', models.FloatField(verbose_name='X минимум')),
                ('x_max', models.FloatField(verbose_name='X максимум')),
                ('x_steps', models.PositiveIntegerField(default=50, verbose_name='Количество точек')),
                ('chart_type', models.CharField(choices=[('line', 'Линейный'), ('scatter', 'Точечный'), ('bar', 'Столбчатый')], default='line', max_length=20, verbose_name='Тип графика')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='formulas.formula', verbose_name='Формула (Y)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
        migrations.CreateModel(
            name='FormulaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('old_expression', models.TextField(blank=True, verbose_name='Старое выражение')),
                ('new_expression', models.TextField(blank=True, verbose_name='Новое выражение')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Старые значения')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Новые значения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='formulas.formula', verbose_name='Формула')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История формулы',
                'verbose_name_plural': 'История формул',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер варианта')),
                ('student_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО студента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='formulas.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'ordering': ['project', 'number'],
                'unique_together': {('project', 'number')},
            },
        ),
        migrations.CreateModel(
            name='FormulaVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Символ должен начинаться с буквы и содержать только латинские буквы, цифры и подчёркивание', regex='^[a-zA-Z_][a-zA-Z0-9_]*$')], verbose_name='Символ переменной')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('var_type', models.CharField(choices=[('input', 'Ввод вручную'), ('formula', 'Результат другой формулы')], default='input', max_length=20, verbose_name='Тип')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('default_value', models.FloatField(blank=True, null=True, verbose_name='Значение по умолчанию')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='formulas.formula', verbose_name='Формула')),
                ('source_formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_variable_in', to='formulas.formula', verbose_name='Формула-источник')),
            ],
            options={
                'verbose_name': 'Переменная формулы',
                'verbose_name_plural': 'Переменные формул',
                'ordering': ['symbol'],
                'unique_together': {('formula', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='SessionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='Вычислено автоматически')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_values', to='formulas.formula', verbose_name='Формула')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='formulas.calculationsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Значение сессии',
                'verbose_name_plural': 'Значения сессий',
                'unique_together': {('session', 'formula')},
            },
        ),
        migrations.CreateModel(
            name='VariantGenerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(verbose_name='Минимальное значение')),
                ('max_value', models.FloatField(verbose_name='Максимальное значение')),
                ('step', models.FloatField(default=1, verbose_name='Шаг')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_rules', to='formulas.formula', verbose_name='Формула (входной параметр)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_rules', to='formulas.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Правило генерации',
                'verbose_name_plural': 'Правила генерации',
                'unique_together': {('project', 'formula')},
            },
        ),
        migrations.CreateModel(
            name='VariantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('is_input', models.BooleanField(default=True, verbose_name='Введено вручную')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='formulas.formula', verbose_name='Формула')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='formulas.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Значение варианта',
                'verbose_name_plural': 'Значения вариантов',
                'unique_together': {('variant', 'formula')},
            },
        ),
    ]
