# Generated by Django 5.2.9 on 2026-01-06 09:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Вариант 1 - Иванов', max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сессия вычислений',
                'verbose_name_plural': 'Сессии вычислений',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='formulas.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Уникальный идентификатор (например: K, Re, alpha1)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Символ должен начинаться с буквы и содержать только латинские буквы, цифры и подчёркивание', regex='^[a-zA-Z_][a-zA-Z0-9_]*$')], verbose_name='Символ')),
                ('name', models.CharField(help_text='Понятное название формулы', max_length=200, verbose_name='Название')),
                ('expression', models.TextField(help_text='Математическое выражение (например: R1 * (1 - cos(alpha)))', verbose_name='Выражение')),
                ('unit', models.CharField(blank=True, help_text='Единица измерения результата (например: м, кг, Вт)', max_length=50, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, help_text='Подробное описание формулы', verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_input', models.BooleanField(default=False, help_text='Если отмечено - это входное значение, а не вычисляемая формула', verbose_name='Входной параметр')),
                ('default_value', models.FloatField(blank=True, null=True, verbose_name='Значение по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulas', to='formulas.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Формула',
                'verbose_name_plural': 'Формулы',
                'ordering': ['category', 'order', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='FormulaVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Символ должен начинаться с буквы и содержать только латинские буквы, цифры и подчёркивание', regex='^[a-zA-Z_][a-zA-Z0-9_]*$')], verbose_name='Символ переменной')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('var_type', models.CharField(choices=[('input', 'Ввод вручную'), ('formula', 'Результат другой формулы')], default='input', max_length=20, verbose_name='Тип')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('default_value', models.FloatField(blank=True, null=True, verbose_name='Значение по умолчанию')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='formulas.formula', verbose_name='Формула')),
                ('source_formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_as_variable_in', to='formulas.formula', verbose_name='Формула-источник')),
            ],
            options={
                'verbose_name': 'Переменная формулы',
                'verbose_name_plural': 'Переменные формул',
                'ordering': ['symbol'],
                'unique_together': {('formula', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='SessionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='Вычислено автоматически')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_values', to='formulas.formula', verbose_name='Формула')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='formulas.calculationsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Значение сессии',
                'verbose_name_plural': 'Значения сессий',
                'unique_together': {('session', 'formula')},
            },
        ),
    ]
