# Generated by Django 5.2.9 on 2026-01-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='expression',
            field=models.TextField(blank=True, default='', help_text='Математическое выражение (например: R1 * (1 - cos(alpha)))', verbose_name='Выражение'),
        ),
    ]
