# Generated by Django 5.2.9 on 2026-04-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='formulas_snapshot',
            field=models.JSONField(blank=True, help_text='JSON с формулами на момент создания варианта', null=True, verbose_name='Снимок формул'),
        ),
    ]
