# Generated by Django 5.2.9 on 2026-01-06 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_alter_formula_expression'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FormulaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('old_expression', models.TextField(blank=True, verbose_name='Старое выражение')),
                ('new_expression', models.TextField(blank=True, verbose_name='Новое выражение')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Старые значения')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Новые значения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='formulas.formula', verbose_name='Формула')),
            ],
            options={
                'verbose_name': 'История формулы',
                'verbose_name_plural': 'История формул',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер варианта')),
                ('student_name', models.CharField(blank=True, max_length=200, verbose_name='ФИО студента')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='formulas.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
                'ordering': ['project', 'number'],
                'unique_together': {('project', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VariantGenerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField(verbose_name='Минимальное значение')),
                ('max_value', models.FloatField(verbose_name='Максимальное значение')),
                ('step', models.FloatField(default=1, verbose_name='Шаг')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_rules', to='formulas.formula', verbose_name='Формула (входной параметр)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_rules', to='formulas.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Правило генерации',
                'verbose_name_plural': 'Правила генерации',
                'unique_together': {('project', 'formula')},
            },
        ),
        migrations.CreateModel(
            name='VariantValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Значение')),
                ('is_input', models.BooleanField(default=True, verbose_name='Введено вручную')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='formulas.formula', verbose_name='Формула')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='formulas.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Значение варианта',
                'verbose_name_plural': 'Значения вариантов',
                'unique_together': {('variant', 'formula')},
            },
        ),
    ]
