# Generated by Django 5.2.9 on 2026-01-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_project_formulahistory_variant_variantgenerationrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulahistory',
            name='formula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='formulas.formula', verbose_name='Формула'),
        ),
        migrations.CreateModel(
            name='FormulaChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название графика')),
                ('x_variable', models.CharField(help_text='Символ переменной для оси X', max_length=50, verbose_name='Переменная по оси X')),
                ('x_min', models.FloatField(verbose_name='X минимум')),
                ('x_max', models.FloatField(verbose_name='X максимум')),
                ('x_steps', models.PositiveIntegerField(default=50, verbose_name='Количество точек')),
                ('chart_type', models.CharField(choices=[('line', 'Линейный'), ('scatter', 'Точечный'), ('bar', 'Столбчатый')], default='line', max_length=20, verbose_name='Тип графика')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='formulas.formula', verbose_name='Формула (Y)')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
            },
        ),
    ]
