# Generated by Django 5.2.9 on 2026-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_variant_formulas_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='last_recalculated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего пересчёта'),
        ),
    ]
