# Generated by Django 5.2.9 on 2026-04-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_variant_last_recalculated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormulaHistory',
        ),
    ]
