# Generated by Django 5.2.9 on 2026-04-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0005_delete_formulahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulachart',
            name='invert_y',
            field=models.BooleanField(default=False, verbose_name='Инвертировать ось Y'),
        ),
        migrations.AlterField(
            model_name='formulachart',
            name='x_max',
            field=models.FloatField(default=0.0, verbose_name='X максимум'),
        ),
        migrations.AlterField(
            model_name='formulachart',
            name='x_min',
            field=models.FloatField(default=0.0, verbose_name='X минимум'),
        ),
    ]
